import type { Metadata } from "next";
import { Geist, Geist_Mono, Space_Mono, Oswald, Barlow_Condensed } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const barlowCondensed = Barlow_Condensed({
  variable: "--font-barlow-condensed",
  subsets: ["latin"],
  weight: ["700", "900"],
});

const spaceMono = Space_Mono({
  variable: "--font-space-mono",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${spaceMono.variable} ${oswald.variable} ${barlowCondensed.variable} antialiased`}
      >
        <Header
          navLinks={[
            { label: "Signals",      href: "/signals" },
            { label: "Sportsbooks",  href: "/sportsbooks" },
            { label: "Hotsheet",     href: "/hotsheet" },
            { label: "Pricing",      href: "/pricing" },
          ]}
        />
        {children}
        <Footer
          description="Confidence-scored betting signals for every sport. Priced by conviction. Backed by the model. Not a sportsbook."
          copyright="© 2028 WagerBird. All rights reserved."
          sections={[
            {
              title: "Products",
              links: [
                { label: "Terminal", href: "/" },
                { label: "Signals", href: "/signals" },
                { label: "Sportsbooks", href: "/sportsbooks" },
                { label: "Hotsheet", href: "/hotsheet" },
                { label: "Packs", href: "/packs" },
              ],
            },
            {
              title: "Resources",
              links: [
                { label: "Results", href: "/results" },
                { label: "Live Odds", href: "/live-odds" },
                { label: "FAQ", href: "/faq" },
              ],
            },
            {
              title: "Company",
              links: [
                { label: "About", href: "/about" },
                { label: "Contact", href: "/contact" },
                { label: "Privacy Policy", href: "/privacy-policy" },
                { label: "Terms of Service", href: "/terms-of-service" },
              ],
            },
          ]}
        />
      </body>
    </html>
  );
}
