"use client";

import { useRef, useEffect, useState } from "react";
import type { QuantumPageResult } from "@/sanity/lib/queries";

const DEFAULT_HERO_VIDEO =
  "https://cdn.builder.io/o/assets%2F72558899b84e49bc881d9b8ba6c19012%2F65433c5f34e8436faa97bd9d7d3900e1?alt=media&token=382fe1b8-0458-4190-8110-3b732e8caf0a&apiKey=72558899b84e49bc881d9b8ba6c19012";

const DEFAULT_PILLARS = [
  { num: "01", title: "Personal Trader", tag: "Direct Comm Line", desc: "A dedicated risk manager assigned to your portfolio. They filter signals, size positions relative to your bankroll, and provide rationale for every execution." },
  { num: "02", title: "Money Management", tag: "Capital Preservation", desc: "Strict institutional drawdown protocols applied to your account. We prioritize protecting the principal while compounding the alpha generated by our models." },
  { num: "03", title: "Institutional Feeds", tag: "Unrestricted Access", desc: "Raw access to the same latency-optimized API feeds and sharp money indicators used by our internal proprietary trading desk." },
  { num: "04", title: "Full Platform", tag: "Command Center", desc: "Log in to your private terminal to view live risk, historical performance analytics, and real-time market sentiment dashboards." },
];

const DEFAULT_TIERS = [
  { label: "Tier I", name: "Ascent", features: ["Dedicated Associate Trader", "Core Market Feeds", "Standard Risk Protocols"], footerText: "Min. Bankroll: $50k", featured: false, featuredBadge: "" },
  { label: "Tier II", name: "Summit", features: ["Senior Portfolio Manager", "Horizon & Pulse Access", "Custom Hedging Strategy", "Weekly Strategy Briefing"], footerText: "Min. Bankroll: $250k", featured: true, featuredBadge: "Most Selected" },
  { label: "Tier III", name: "Apex", features: ["Desk Head Assignment", "Bespoke Model Requests", "API Execution Routing"], footerText: "By Invitation Only", featured: false, featuredBadge: "" },
];

const DEFAULT_RIGHT_FIT = [
  "Investors treating sports markets as an alternative asset class.",
  "Individuals with strict emotional discipline and long-term horizon.",
  "Capital bases requiring institutional risk management architecture.",
];

const DEFAULT_MISALIGNED = [
  "Recreational bettors looking for daily action or \"locks\".",
  "Those unable to tolerate variance or adhere to strict unit sizing.",
  "Individuals seeking immediate, short-term financial returns.",
];

function IconArrowRight() {
  return (
    <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" className="qb-icon-arrow">
      <path d="M6 12L10 8L6 4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="square" />
    </svg>
  );
}

function IconCheck() {
  return (
    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <path d="M5 13l4 4L19 7" />
    </svg>
  );
}

function IconMinus() {
  return (
    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <path d="M8 12h8" />
    </svg>
  );
}

export default function QuantumPageContent({ data }: { data: QuantumPageResult | null }) {
  const platformsRef = useRef<HTMLElement>(null);
  const [revealed, setRevealed] = useState(false);
  const [gaugesAnimated, setGaugesAnimated] = useState(false);

  const [form, setForm] = useState({
    firstName: "",
    lastName: "",
    email: "",
    phone: "",
    tierOfInterest: "",
    capitalCommitment: "50k-250k",
    primaryMarkets: "",
    confirmed: false,
  });
  const [submitStatus, setSubmitStatus] = useState<"idle" | "submitting" | "success" | "error">("idle");
  const [submitError, setSubmitError] = useState<string | null>(null);

  const handleFormChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    const target = e.target;
    const value = target.type === "checkbox" ? (target as HTMLInputElement).checked : target.value;
    setForm((prev) => ({ ...prev, [target.name]: value }));
  };

  const isFormValid =
    form.firstName.trim().length > 0 &&
    form.lastName.trim().length > 0 &&
    form.email.trim().length > 0 &&
    form.phone.trim().length > 0 &&
    form.tierOfInterest.length > 0 &&
    form.confirmed;

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setSubmitStatus("submitting");
    setSubmitError(null);
    try {
      const res = await fetch("/api/quantum-submit", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          firstName: form.firstName.trim(),
          lastName: form.lastName.trim(),
          email: form.email.trim(),
          phone: form.phone.trim(),
          tierOfInterest: form.tierOfInterest || undefined,
          capitalCommitment: form.capitalCommitment || undefined,
          primaryMarkets: form.primaryMarkets.trim() || undefined,
        }),
      });
      const json = await res.json();
      if (!res.ok) {
        throw new Error(json.error ?? "Something went wrong.");
      }
      setSubmitStatus("success");
      setForm({ firstName: "", lastName: "", email: "", phone: "", tierOfInterest: "", capitalCommitment: "50k-250k", primaryMarkets: "", confirmed: false });
    } catch (err) {
      setSubmitStatus("error");
      setSubmitError(err instanceof Error ? err.message : "Failed to submit. Please try again.");
    }
  };

  const c = {
    heroBadgeText: data?.heroBadgeText ?? "Private Client Program · By Qualification",
    heroTitleLine1: data?.heroTitleLine1 ?? "Where precision",
    heroTitleLine2: data?.heroTitleLine2 ?? "conviction",
    heroSub: data?.heroSub ?? "Quantum is WagerBird's private advisory program — a dedicated relationship between you, your personal trader, and institutional-grade intelligence that doesn't exist on the open market.",
    heroPrimaryCtaLabel: data?.heroPrimaryCtaLabel ?? "Request Access",
    heroPrimaryCtaHref: data?.heroPrimaryCtaHref ?? "#apply",
    heroSecondaryCtaLabel: data?.heroSecondaryCtaLabel ?? "See What's Included",
    heroSecondaryCtaHref: data?.heroSecondaryCtaHref ?? "#program",
    heroVideoUrl: data?.heroVideoUrl || DEFAULT_HERO_VIDEO,
    heroMetaItems: data?.heroMetaItems?.length ? data.heroMetaItems : ["Personal Trader Assigned", "Institutional Data Feeds", "Bespoke Signal Delivery"],
    introTitle: data?.introTitle ?? "A relationship,\nnot a subscription.",
    introParagraph1: data?.introParagraph1 ?? "The retail betting market is designed to extract capital through friction, obscured margins, and emotional volatility. Institutional markets operate on a fundamentally different axis: cold logic, deep data, and absolute discipline.",
    introParagraph2: data?.introParagraph2 ?? "Quantum bridges this divide for high-net-worth individuals. By pairing serious capital with a dedicated relationship manager and proprietary trading feeds, we replace guesswork with systematic edge. You are not buying picks; you are integrating into a private trading desk.",
    pillarsEyebrow: data?.pillarsEyebrow ?? "What you receive",
    pillarsTitle: data?.pillarsTitle ?? "Four pillars.\nOne integrated edge.",
    pillarsCards: (data?.pillarsCards?.length ? data.pillarsCards : DEFAULT_PILLARS) as { num?: string; title?: string; tag?: string; desc?: string }[],
    platformsEyebrow: data?.platformsEyebrow ?? "Quantum Platforms",
    platformsTitle: data?.platformsTitle ?? "Three systems.\nOne edge.",
    platformsDescription: data?.platformsDescription ?? "Quantum clients receive full access to the Terminal and exclusive access to two proprietary platforms unavailable to general subscribers. Each purpose-built for a different layer of the intelligence stack.",
    platformAdvisory: { tag: data?.platformAdvisoryTag ?? "Core Program", name: data?.platformAdvisoryName ?? "Quantum Advisory", sub: data?.platformAdvisorySub ?? "Full advisory relationship", badge: data?.platformAdvisoryBadge ?? "All Tiers", desc: data?.platformAdvisoryDesc ?? "The full advisory relationship. Your trader, your data, your strategy — coordinated through WagerBird's Terminal with institutional precision." },
    platformHorizon: { tag: data?.platformHorizonTag ?? "Exclusive Platform", name: data?.platformHorizonName ?? "Horizon", sub: data?.platformHorizonSub ?? "Institutional Feed · Live Market", badge: data?.platformHorizonBadge ?? "Summit + Apex", desc: data?.platformHorizonDesc ?? "Surfaces book movement, line drift, and sharp-side pressure in real time — the view professional operations rely on." },
    platformPulse: { tag: data?.platformPulseTag ?? "Exclusive Platform", name: data?.platformPulseName ?? "Pulse", sub: data?.platformPulseSub ?? "In-Game Intelligence Display", badge: data?.platformPulseBadge ?? "Summit + Apex", desc: data?.platformPulseDesc ?? "Dynamic market signals and in-game conviction scoring. The fastest read on where the market is moving and why." },
    structureTitle: data?.structureTitle ?? "Built for\nserious capital.",
    structureNote: data?.structureNote ?? "Performance-based only.\nNo upfront advisory fees.",
    tiers: (data?.tiers?.length ? data.tiers : DEFAULT_TIERS) as { label?: string; name?: string; features?: string[]; footerText?: string; featured?: boolean; featuredBadge?: string }[],
    qualRightFitTitle: data?.qualRightFitTitle ?? "Right Fit",
    qualRightFitItems: data?.qualRightFitItems?.length ? data.qualRightFitItems : DEFAULT_RIGHT_FIT,
    qualMisalignedTitle: data?.qualMisalignedTitle ?? "Misaligned",
    qualMisalignedItems: data?.qualMisalignedItems?.length ? data.qualMisalignedItems : DEFAULT_MISALIGNED,
    applyTitle: data?.applyTitle ?? "Start the conversation.",
    applyNote: data?.applyNote ?? "Please provide accurate details. Our advisory team reviews applications weekly.",
    applyDisclaimer: data?.applyDisclaimer ?? "Strictly confidential · Limited quarterly enrollment",
    applyCheckboxText: data?.applyCheckboxText ?? "I confirm I meet the capital requirements and understand this application is for a private advisory relationship, not a guaranteed return product.",
    applySubmitLabel: data?.applySubmitLabel ?? "Submit Application",
  };

  useEffect(() => {
    const el = platformsRef.current;
    if (!el) return;
    const obs = new IntersectionObserver(
      (entries) => {
        if (entries[0]?.isIntersecting) {
          setRevealed(true);
          setTimeout(() => setGaugesAnimated(true), 300);
        }
      },
      { threshold: 0.06 }
    );
    obs.observe(el);
    return () => obs.disconnect();
  }, []);

  return (
    <div className="qb-page">
      {/* Hero */}
      <section className="qb-hero">
        <div className="qb-hero-bg">
          <video autoPlay loop muted playsInline className="qb-hero-video" src={c.heroVideoUrl} />
          <div className="qb-hero-overlay" />
          <div className="qb-hero-glow" />
          <div className="qb-hero-scanlines" />
          <div className="qb-hero-ghost-q" aria-hidden>Q</div>
        </div>
        <div className="qb-hero-inner">
          <div className="qb-hero-content">
            <div className="qb-badge">
              <span className="qb-badge-dot" />
              <span className="qb-badge-text">{c.heroBadgeText}</span>
            </div>
            <h1 className="qb-hero-title">
              {c.heroTitleLine1}
              <br />
              meets <em>{c.heroTitleLine2}</em>
            </h1>
            <p className="qb-hero-sub">{c.heroSub}</p>
            <div className="qb-hero-actions">
              <a href={c.heroPrimaryCtaHref} className="qb-btn-outline">
                <span>{c.heroPrimaryCtaLabel}</span>
                <IconArrowRight />
              </a>
              <a href={c.heroSecondaryCtaHref} className="qb-btn-ghost">
                {c.heroSecondaryCtaLabel}
              </a>
            </div>
            <div className="qb-hero-meta">
              {c.heroMetaItems.map((label, i) => (
                <span key={i}>
                  {i === 0 && <svg className="qb-meta-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2" /><circle cx="12" cy="7" r="4" /></svg>}
                  {i === 1 && <svg className="qb-meta-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><rect x="2" y="2" width="20" height="8" rx="2" /><path d="M6 22V12M18 22V12" /></svg>}
                  {i === 2 && <svg className="qb-meta-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><circle cx="12" cy="12" r="3" /><path d="M12 2v2M12 20v2M2 12h2M20 12h2" /></svg>}
                  {label}
                </span>
              ))}
            </div>
          </div>
        </div>
        <div className="qb-hero-fade" />
      </section>

      {/* Intro */}
      <section id="program" className="qb-intro">
        <div className="qb-intro-grid" />
        <div className="qb-intro-inner">
          <div className="qb-intro-grid-layout">
            <div className="qb-intro-head">
              <h2 className="qb-intro-title">
                {c.introTitle.split("\n").map((line, i, arr) => (
                  <span key={i}>{line}{i < arr.length - 1 && <br />}</span>
                ))}
              </h2>
            </div>
            <div className="qb-intro-body">
              <p>{c.introParagraph1}</p>
              <p>{c.introParagraph2}</p>
            </div>
          </div>
          <div className="qb-divider" />
        </div>
      </section>

      {/* Four pillars */}
      <section className="qb-pillars">
        <div className="qb-pillars-inner">
          <div className="qb-pillars-head">
            <p className="qb-eyebrow">{c.pillarsEyebrow}</p>
            <h2 className="qb-pillars-title">
              {c.pillarsTitle.split("\n").map((line, i, arr) => {
                const parts = line.split(/\b(edge)\b/gi);
                return (
                  <span key={i}>
                    {parts.map((part, j) => (part.toLowerCase() === "edge" ? <em key={`${i}-${j}`}>{part}</em> : part))}
                    {i < arr.length - 1 && <br />}
                  </span>
                );
              })}
            </h2>
          </div>
          <div className="qb-pillars-grid">
            {c.pillarsCards.map((card) => (
              <div key={card.num} className="qb-glass">
                <div className="qb-glass-glow" />
                <div className="qb-glass-inner">
                  <div className="qb-glass-num">{card.num}</div>
                  <h3 className="qb-glass-title">{card.title}</h3>
                  <p className="qb-glass-tag">{card.tag}</p>
                  <p className="qb-glass-desc">{card.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Platforms */}
      <section ref={platformsRef} className="qb-platforms">
        <div className="qb-platforms-inner">
          <div className={`qb-platforms-head rv ${revealed ? "in" : ""}`}>
            <div className="eyebrow-v4">{c.platformsEyebrow}</div>
            <h2 className="dh-v4">
              {c.platformsTitle.split("\n").map((line, i, arr) => (
                <span key={i}>{line.split(/\b(edge)\b/gi).map((part, j) => part.toLowerCase() === "edge" ? <em key={j}>{part}</em> : part)}{i < arr.length - 1 && <br />}</span>
              ))}
            </h2>
            <p>{c.platformsDescription}</p>
          </div>
          <div className="plat-grid-v4">
            {/* Quantum Advisory */}
            <div className={`plat-card-v4 rv ${revealed ? "in" : ""}`}>
              <div className="pc-header-v4">
                <div className="pc-tag-v4">{c.platformAdvisory.tag}</div>
                <div className="pc-name-v4">{c.platformAdvisory.name}</div>
                <div className="pc-sub-v4">{c.platformAdvisory.sub}</div>
                <span className="pc-badge-v4">{c.platformAdvisory.badge}</span>
              </div>
              <div className="pc-preview-v4">
                <div className="qa-svg-wrap">
                  <svg width="100%" height="100%" viewBox="0 0 200 160" preserveAspectRatio="xMidYMid meet" className="qa-svg">
                    <line className="qa-svg-line" x1="100" y1="80" x2="40" y2="32" stroke="rgba(228,242,34,.12)" strokeWidth="1" strokeDasharray="3,4" />
                    <line className="qa-svg-line" x1="100" y1="80" x2="160" y2="32" stroke="rgba(0,37,225,.2)" strokeWidth="1" strokeDasharray="3,4" />
                    <line className="qa-svg-line" x1="100" y1="80" x2="100" y2="141" stroke="rgba(228,242,34,.1)" strokeWidth="1" strokeDasharray="3,4" />
                    <circle cx="100" cy="80" r="20" fill="rgba(228,242,34,.08)" stroke="rgba(228,242,34,.3)" strokeWidth="1" />
                    <text x="100" y="80" textAnchor="middle" dominantBaseline="middle" className="qa-svg-text">TRADER</text>
                    <circle cx="40" cy="32" r="14" fill="rgba(0,37,225,.1)" stroke="rgba(0,37,225,.3)" strokeWidth="1" />
                    <text x="40" y="32" textAnchor="middle" dominantBaseline="middle" className="qa-svg-text-sm">CLIENT</text>
                    <circle cx="160" cy="32" r="14" fill="rgba(228,242,34,.05)" stroke="rgba(228,242,34,.15)" strokeWidth="1" />
                    <text x="160" y="32" textAnchor="middle" dominantBaseline="middle" className="qa-svg-text-sm">DATA</text>
                    <circle cx="100" cy="141" r="14" fill="rgba(228,242,34,.05)" stroke="rgba(228,242,34,.15)" strokeWidth="1" />
                    <text x="100" y="141" textAnchor="middle" dominantBaseline="middle" className="qa-svg-text-sm">FEED</text>
                    <circle className="qa-orbit-dot" r="3" fill="rgba(228,242,34,0.7)">
                      <animateMotion dur="4s" repeatCount="indefinite" path="M 72,80 A 28,28 0 1,1 128,80 A 28,28 0 1,1 72,80" />
                    </circle>
                  </svg>
                </div>
              </div>
              <div className="pc-desc-area-v4">
                <p className="pc-desc-v4">{c.platformAdvisory.desc}</p>
              </div>
            </div>

            {/* Horizon */}
            <div className={`plat-card-v4 rv rv-d1 ${revealed ? "in" : ""}`}>
              <div className="pc-header-v4">
                <div className="pc-tag-v4">{c.platformHorizon.tag}</div>
                <div className="pc-name-v4">{c.platformHorizon.name}</div>
                <div className="pc-sub-v4">{c.platformHorizon.sub}</div>
                <span className="pc-badge-v4">{c.platformHorizon.badge}</span>
              </div>
              <div className="pc-preview-v4">
                <div className="hz-preview-v4">
                  <div className="hz-label">Live Odds Screen</div>
                  {[
                    { team: "DAL -3.5", odds: "-112 ▲", move: "+4", moveClass: "move" },
                    { team: "PHI +3.5", odds: "+108", move: "-3", moveClass: "" },
                    { team: "KC  -6.5", odds: "-106 ▲", move: "+7", moveClass: "move" },
                    { team: "LV  +6.5", odds: "+114 ▼", move: "-5", moveClass: "down" },
                  ].map((row) => (
                    <div key={row.team} className="hz-row-v4">
                      <span className="hz-team-v4">{row.team}</span>
                      <span className={`hz-odds-v4 ${row.moveClass}`}>{row.odds}</span>
                      <span className="hz-move-v4">{row.move}</span>
                    </div>
                  ))}
                  <div className="hz-chart-wrap">
                    <div className="hz-chart-label">Line Movement</div>
                    <svg viewBox="0 0 200 40" preserveAspectRatio="none" className="hz-chart-svg">
                      <defs>
                        <linearGradient id="lineGrad-v4" x1="0" y1="0" x2="0" y2="1">
                          <stop offset="0%" stopColor="rgba(228,242,34,.3)" />
                          <stop offset="100%" stopColor="rgba(228,242,34,0)" />
                        </linearGradient>
                      </defs>
                      <path className="hz-chart-line" d="M0,32 L20,28 L40,26 L60,20 L80,18 L100,14 L120,10 L140,8 L160,6 L180,4 L200,2" fill="none" stroke="rgba(228,242,34,.5)" strokeWidth="1.5" />
                      <path d="M0,32 L20,28 L40,26 L60,20 L80,18 L100,14 L120,10 L140,8 L160,6 L180,4 L200,2 L200,40 L0,40Z" fill="url(#lineGrad-v4)" />
                      <circle cx="200" cy="2" r="2.5" fill="rgba(228,242,34,.9)">
                        <animate attributeName="opacity" values="1;0.2;1" dur="1.5s" repeatCount="indefinite" />
                      </circle>
                    </svg>
                  </div>
                </div>
              </div>
              <div className="pc-desc-area-v4">
                <p className="pc-desc-v4">{c.platformHorizon.desc}</p>
              </div>
            </div>

            {/* Pulse */}
            <div className={`plat-card-v4 rv rv-d2 ${revealed ? "in" : ""}`}>
              <div className="pc-header-v4">
                <div className="pc-tag-v4">{c.platformPulse.tag}</div>
                <div className="pc-name-v4">{c.platformPulse.name}</div>
                <div className="pc-sub-v4">{c.platformPulse.sub}</div>
                <span className="pc-badge-v4">{c.platformPulse.badge}</span>
              </div>
              <div className="pc-preview-v4">
                <div className="ps-preview-v4">
                  <div className="ps-label">Live Conviction Gauges</div>
                  {[
                    { label: "WIN PROB", width: "78%", val: "78%", color: "" },
                    { label: "CONF", width: "91%", val: "91", color: "bright" },
                    { label: "SHARP %", width: "64%", val: "64%", color: "blue" },
                    { label: "EDGE", width: "44%", val: "+4.4", color: "edge" },
                  ].map((g) => (
                    <div key={g.label} className="ps-gauge-wrap-v4">
                      <span className="ps-gauge-label-v4">{g.label}</span>
                      <div className="ps-gauge-track-v4">
                        <div className={`ps-gauge-fill-v4 ${g.color}`} style={{ width: gaugesAnimated ? g.width : "0%" }} data-width={g.width} />
                      </div>
                      <span className={`ps-gauge-val-v4 ${g.color}`}>{g.val}</span>
                    </div>
                  ))}
                  <div className="ps-momentum-v4">
                    <div className="ps-momentum-label-v4">Market Momentum</div>
                    <div className="ps-bars-v4">
                      {[20, 35, 28, 55, 72, 85, 92, 100].map((h, i) => (
                        <div key={i} className={`ps-bar-v4 ${i >= 4 ? "hot" : ""}`} style={{ height: `${h}%` }}>
                          {i === 7 && <span className="ps-bar-blink" />}
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              </div>
              <div className="pc-desc-area-v4">
                <p className="pc-desc-v4">{c.platformPulse.desc}</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Program structure */}
      <section id="structure" className="qb-structure">
        <div className="qb-structure-inner">
          <div className="qb-structure-head">
            <h2 className="qb-structure-title">
              {c.structureTitle.split("\n").map((line, i, arr) => (
                <span key={i}>{line}{i < arr.length - 1 && <br />}</span>
              ))}
            </h2>
            <p className="qb-structure-note">
              {c.structureNote.split("\n").map((line, i, arr) => (
                <span key={i}>{line}{i < arr.length - 1 && <br />}</span>
              ))}
            </p>
          </div>
          <div className="qb-tiers">
            {c.tiers.map((tier, idx) => (
              <div key={idx} className={`qb-tier-card ${tier.featured ? "qb-tier-featured" : ""}`}>
                {tier.featured && tier.featuredBadge && (
                  <>
                    <div className="qb-tier-badge">{tier.featuredBadge}</div>
                    <div className="qb-tier-glow" />
                  </>
                )}
                <h3 className={`qb-tier-label ${tier.featured ? "yellow" : ""}`}>{tier.label}</h3>
                <div className="qb-tier-name">{tier.name}</div>
                <ul className="qb-tier-list">
                  {(tier.features ?? []).map((feature, i) => (
                    <li key={i}><IconCheck /> {feature}</li>
                  ))}
                </ul>
                <div className={`qb-tier-footer ${tier.featured ? "qb-tier-footer-flex" : ""}`}>
                  <span>{tier.footerText}</span>
                  {tier.featured && (
                    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="M12 2v4M12 18v4M4.93 4.93l2.83 2.83M16.24 16.24l2.83 2.83M2 12h4M18 12h4M4.93 19.07l2.83-2.83M16.24 7.76l2.83-2.83" /></svg>
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Qualification */}
      <section className="qb-qual">
        <div className="qb-qual-inner">
          <div className="qb-qual-grid">
            <div className="qb-qual-col">
              <h3 className="qb-qual-head"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><circle cx="12" cy="12" r="10" /><circle cx="12" cy="12" r="6" /><circle cx="12" cy="12" r="2" /></svg> {c.qualRightFitTitle}</h3>
              <ul>
                {c.qualRightFitItems.map((item, i) => (
                  <li key={i}><IconCheck /><span>{item}</span></li>
                ))}
              </ul>
            </div>
            <div className="qb-qual-col">
              <h3 className="qb-qual-head misaligned"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="M18 6L6 18M6 6l12 12" /></svg> {c.qualMisalignedTitle}</h3>
              <ul>
                {c.qualMisalignedItems.map((item, i) => (
                  <li key={i}><IconMinus /><span>{item}</span></li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      </section>

      {/* Application */}
      <section id="apply" className="qb-apply">
        <div className="qb-apply-glow" />
        <div className="qb-apply-inner">
          <div className="qb-apply-card">
            <div className="qb-apply-corner" />
            <div className="qb-apply-head">
              <h2 className="qb-apply-title">{c.applyTitle}</h2>
              <p className="qb-apply-note">{c.applyNote}</p>
            </div>
            <form
              className="qb-form"
              onSubmit={handleSubmit}
            >
              {submitStatus === "success" && (
                <p className="qb-form-success" role="alert">
                  Thank you. Your application has been received. Our advisory team will review it and be in touch.
                </p>
              )}
              {submitStatus === "error" && submitError && (
                <p className="qb-form-error" role="alert">
                  {submitError}
                </p>
              )}
              <div className="qb-form-row">
                <div className="qb-field">
                  <label htmlFor="qb-firstName">First Name</label>
                  <input id="qb-firstName" name="firstName" type="text" required value={form.firstName} onChange={handleFormChange} disabled={submitStatus === "submitting"} />
                </div>
                <div className="qb-field">
                  <label htmlFor="qb-lastName">Last Name</label>
                  <input id="qb-lastName" name="lastName" type="text" required value={form.lastName} onChange={handleFormChange} disabled={submitStatus === "submitting"} />
                </div>
              </div>
              <div className="qb-form-row">
                <div className="qb-field">
                  <label htmlFor="qb-email">Email Address</label>
                  <input id="qb-email" name="email" type="email" required value={form.email} onChange={handleFormChange} disabled={submitStatus === "submitting"} />
                </div>
                <div className="qb-field">
                  <label htmlFor="qb-phone">Phone Number</label>
                  <input id="qb-phone" name="phone" type="tel" required value={form.phone} onChange={handleFormChange} disabled={submitStatus === "submitting"} />
                </div>
              </div>
              <div className="qb-form-row">
                <div className="qb-field">
                  <label htmlFor="qb-tier">Tier of Interest</label>
                  <select id="qb-tier" name="tierOfInterest" required value={form.tierOfInterest} onChange={handleFormChange} disabled={submitStatus === "submitting"}>
                    <option value="">Select Tier</option>
                    <option value="ascent">Ascent (Tier I)</option>
                    <option value="summit">Summit (Tier II)</option>
                    <option value="apex">Apex (Tier III)</option>
                  </select>
                </div>
                <div className="qb-field">
                  <label htmlFor="qb-capital">Capital Commitment</label>
                  <select id="qb-capital" name="capitalCommitment" value={form.capitalCommitment} onChange={handleFormChange} disabled={submitStatus === "submitting"}>
                    <option value="50k-250k">$50k - $250k</option>
                    <option value="250k-1m">$250k - $1M</option>
                    <option value="1m+">$1M+</option>
                  </select>
                </div>
              </div>
              <div className="qb-field">
                <label htmlFor="qb-markets">Primary Markets of Interest</label>
                <input id="qb-markets" name="primaryMarkets" type="text" placeholder="e.g., NFL, Global Soccer, Tennis" value={form.primaryMarkets} onChange={handleFormChange} disabled={submitStatus === "submitting"} />
              </div>
              <div className="qb-checkbox-wrap">
                <label className="qb-checkbox">
                  <input type="checkbox" name="confirmed" required checked={form.confirmed} onChange={handleFormChange} disabled={submitStatus === "submitting"} />
                  <span className="qb-checkbox-box" />
                  <span className="qb-checkbox-text">{c.applyCheckboxText.split(/\b(relationship)\b/gi).map((part, i) => part.toLowerCase() === "relationship" ? <em key={i}>{part}</em> : part)}</span>
                </label>
              </div>
              <div className="qb-form-footer">
                <p className="qb-form-disclaimer">{c.applyDisclaimer}</p>
                <button type="submit" className="qb-btn-submit" disabled={submitStatus === "submitting" || !isFormValid}>
                  {submitStatus === "submitting" ? "Submitting…" : c.applySubmitLabel}
                </button>
              </div>
            </form>
          </div>
        </div>
      </section>
    </div>
  );
}
