"use client";

import Hero from "@/components/Hero";
import Ticker from "@/components/Ticker";
import Signals from "@/components/Signals";
import ValueStrip from "@/components/ValueStrip";
import Packs from "@/components/Packs";
import Faq from "@/components/Faq";
import CtaBanner from "@/components/CtaBanner";

const terminalFaqs = [
  {
    question: "What is a 'Signal'?",
    answer: "A signal is a professional-grade betting insight generated by our proprietary model. Unlike a standard 'pick', each signal includes a confidence score (1-100) and detailed market analysis.",
  },
  {
    question: "How do I unlock signals?",
    answer: "Signals can be unlocked using WagerBird points. Each signal's cost in points matches its confidence score—a 90-confidence play costs 90 points to uncover.",
  },
  {
    question: "Which sports are covered?",
    answer: "We provide high-conviction signals across MLB, NBA, NFL, NHL, and major Soccer leagues. Coverage expands during peak season for each sport.",
  },
  {
    question: "Are signals guaranteed wins?",
    answer: "No professional sports bettor guarantees wins. We provide a documented mathematical edge. Over a long-term sample, our high-confidence signals (85+) have a proven winning track record.",
  },
  {
    question: "When are new signals posted?",
    answer: "Signals are posted in real-time as market conditions meet our model's criteria. This typically happens between 10:00 AM and 6:00 PM EST daily.",
  },
];

export default function TerminalPage() {
  return (
    <main>
      <Hero
        tickerText="Live Terminal Active — Real-Time Signal Feed"
        badgeText="THE TERMINAL · REAL-TIME SIGNALS"
        title={
          <>
            The<br />
            Terminal. <em className="text-brand-yellow italic font-bold">Real-Time</em><br />
            Signals.
          </>
        }
        description="Access the same data the pros use. Confidence-scored signals delivered in real-time. Stop guessing and start trading with an edge."
        primaryCtaLabel="Explore Signals →"
        primaryCtaHref="#terminal"
        secondaryCtaLabel="View Pricing"
        secondaryCtaHref="/pricing"
        imageUrl="https://api.builder.io/api/v1/image/assets/TEMP/e7a48826f4f3592b62edc4a4adaa3da19d8075e3"
        stats={[
          { value: "40+", label: "Daily Signals" },
          { value: "88%", label: "Max Confidence" },
          { value: "24/7", label: "Market Monitoring" },
        ]}
      />

      <Ticker />

      <div id="terminal">
        <Signals
          title={
            <>
              Live<br />
              <em className="signals-heading-accent">Terminal.</em>
            </>
          }
        />
      </div>

      <ValueStrip />

      <Packs
        title={
          <>
            Need Points?<br />
            <em className="packs-heading-accent">Unlock More.</em>
          </>
        }
      />

      <Faq
        title={
          <>
            Terminal
            <br />
            <em className="faq-heading-accent">Intelligence.</em>
          </>
        }
        items={terminalFaqs}
      />

      <CtaBanner 
        watermark="DATA"
        title={
          <>
            Market Edge.<br />
            Scored in Seconds.
          </>
        }
        subtitle="Join 12,000+ traders using WagerBird to beat the books."
        ctaLabel="Unlock First Signal →"
        ctaHref="#terminal"
      />
    </main>
  );
}
