import { pageType } from "./page";
import { siteSettingsType } from "./siteSettings";
import {
  signInPageType,
  registerPageType,
  notFoundPageType,
  error500PageType,
  comingSoonMetaType,
  affiliatesPageType,
} from "./systemPages";
import {
  heroBlock,
  tickerBlock,
  signalsBlock,
  packsBlock,
  howItWorksBlock,
  faqBlock,
  ctaBannerBlock,
  valueStripBlock,
  hotsheetBlock,
  hotsheetPromoBlock,
  hotsheetFeaturesBlock,
  hotsheetPricingBlock,
  hotsheetWhyBlock,
  proofSectionBlock,
  processSectionBlock,
  emailCaptureBlock,
  sportsbooksHeroBlock,
  sportsbooksSectionBlock,
  accessModelsBlock,
  mapSectionBlock,
} from "./blocks";
import { objectTypes } from "./objects";

export const schemaTypes = [
  pageType,
  siteSettingsType,
  signInPageType,
  registerPageType,
  notFoundPageType,
  error500PageType,
  comingSoonMetaType,
  affiliatesPageType,
  heroBlock,
  tickerBlock,
  signalsBlock,
  packsBlock,
  howItWorksBlock,
  faqBlock,
  ctaBannerBlock,
  valueStripBlock,
  hotsheetBlock,
  hotsheetPromoBlock,
  hotsheetFeaturesBlock,
  hotsheetPricingBlock,
  hotsheetWhyBlock,
  proofSectionBlock,
  processSectionBlock,
  emailCaptureBlock,
  sportsbooksHeroBlock,
  sportsbooksSectionBlock,
  accessModelsBlock,
  mapSectionBlock,
  ...objectTypes,
];
